### ISSUE TITLE
Build on Ubuntu 16.04 fails

### ISSUE THREAD

**Issue by arnold-maderthaner** [Lyndir/MasterPassword#114]
Hi !

I tried to compile the terminal C version on Ubuntu 16.04 but it fails with the following error:

Building target: mpw-tests...
In file included from mpw-tests-util.c:15:0:
mpw-tests-util.h:9:27: fatal error: libxml/parser.h: No such file or directory
compilation terminated.

what can be done to resolve this issue ?

Thanks for your help !

yours

Arnold

**Comment by lhunath** [comment]
Looks like you don't have libxml2 installed.  We look for the headers in `/usr/include/libxml2` and  `/usr/local/include/libxml2`.
